-- Profiles table (extends Supabase Auth)
create table if not exists profiles (
  id uuid references auth.users not null primary key,
  display_name text,
  avatar_url text,
  role text default 'user', -- 'admin' or 'user'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Categories table
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table categories enable row level security;

create policy "Categories are viewable by everyone."
  on categories for select
  using ( true );

create policy "Only admins can insert categories."
  on categories for insert
  with check ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Only admins can update categories."
  on categories for update
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Only admins can delete categories."
  on categories for delete
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- Posts table
create table if not exists posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  content text,
  excerpt text,
  category_id bigint references categories(id),
  featured_image text,
  published boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  author_id uuid references profiles(id)
);

alter table posts enable row level security;

create policy "Published posts are viewable by everyone."
  on posts for select
  using ( published = true );

create policy "Admins can view all posts."
  on posts for select
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Only admins can insert posts."
  on posts for insert
  with check ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Only admins can update posts."
  on posts for update
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Only admins can delete posts."
  on posts for delete
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- Comments table
create table if not exists comments (
  id bigint generated by default as identity primary key,
  content text not null,
  post_id bigint references posts(id) on delete cascade,
  parent_id bigint references comments(id) on delete cascade,
  author_id uuid references profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table comments enable row level security;

create policy "Comments are viewable by everyone."
  on comments for select
  using ( true );

create policy "Authenticated users can insert comments."
  on comments for insert
  with check ( auth.role() = 'authenticated' );

-- Media table (for managing uploads metadata if needed, though Storage is separate)
create table if not exists media (
  id bigint generated by default as identity primary key,
  filename text not null,
  url text not null,
  type text,
  uploaded_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table media enable row level security;

create policy "Media viewable by everyone."
  on media for select
  using ( true );

create policy "Only admins can manage media."
  on media for all
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- Trigger to create profile on signup
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  is_first_user boolean;
begin
  -- Check if any profiles exist
  select not exists (select 1 from public.profiles) into is_first_user;

  insert into public.profiles (id, display_name, role)
  values (
    new.id, 
    new.raw_user_meta_data ->> 'full_name', 
    case when is_first_user then 'admin' else 'user' end
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
